

jobs:
    run-github-actions: 
        runs-on: ubuntu-latest
        steps:
            
            - name: Log Env variables
              run: |
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
                echo "${{ github.token }}"
                # git clone git@github.com:$GITHUB_REPOSITORY.git
                # git checkout $GITHUB_SHA
                pwd
                ls